### ISSUE TITLE
check repeat observations for individuals in coreData

### ISSUE THREAD

**Issue by bletcher** [Conte-Ecology/westBrookData#29]
after running testScript through censor(), there are still some duplicate tag/sampleNumber rows. e.e.

repeatRows <- coreData %>% group_by( tag,sampleNumber ) %>% filter( n() > 1 ) 

> repeatRows
> Source: local data frame [118 x 11]
> Groups: tag, sampleNumber [59]

```
      tag cohort detectionDate sampleNumber      river section species   enc sampleIndex tagIndex ageInSamples
    (chr)  (dbl)        (time)        (dbl)      (chr)   (chr)   (chr) (dbl)       (dbl)    (dbl)        (dbl)
```

1  0009f6ed03   2012    2013-09-19           75 west brook       6     bkt     1          66     3059            5
2  0009f6ed03   2012    2013-09-19           75 west brook       6     bkt     1          66     3059            5
3  0009f6ed03   2012    2013-11-19           76   wb jimmy       3     bkt     1          67     3059            6
4  0009f6ed03   2012    2013-11-19           76   wb jimmy       3     bkt     1          67     3059            6
5  0009f6ed03   2012    2014-04-04           77   wb jimmy       3     bkt     1          68     3059            7
6  0009f6ed03   2012    2014-04-04           77   wb jimmy       3     bkt     1          68     3059            7
7  1bf0fe6349   2000    2001-06-13           26 west brook      43     bkt     1          17     4764            4
8  1bf0fe6349   2000    2001-07-27           26 west brook      36     bkt     1          17     4764            4
9  1bf0fe687c   2000    2001-06-06           26 west brook       9     bkt     1          17     4768            4
10 1bf0fe687c   2000    2001-07-23           26 west brook       9     bkt     1          17     4768            4
..        ...    ...           ...          ...        ...     ...     ...   ...         ...      ...          ...

Need to decide in which function to drop the first obs, or fix it where it is now.

**Comment by evanchildress** [comment]
I fixed part of this problem, which happened in the creation of cohorts when two observations of the fish at its minimum length were in the data. But there is another part: two sample_names (34,35) are grouped into a single sample_number (26), I guess because of the dates. It looks like all sections of the mainstem were sampled both times, so grouping them seems a bit weird, but I'm not sure how to handle it.

**Comment by evanchildress** [comment]
closing, because the multiple sample number issues are included in another issue
