### ISSUE TITLE
make sure these lengths have been dealt with in raw data

### ISSUE THREAD

**Issue by bletcher** [Conte-Ecology/westBrookData#30]
dMData$length[dMData$tagNumberCH=='1BF1FF6207' & dMData$season == 3 & dMData$year == 2005] <- NA
dMData$length[dMData$tagNumberCH=='1BF1FF6521' & dMData$season == 3 & dMData$year == 2005] <- NA
dMData$length[dMData$tagNumberCH=='1BF18CE7ED' & dMData$season == 2 & dMData$year == 2006] <- NA
dMData$length[dMData$tagNumberCH=='1BF20FF1B9' & dMData$season == 3 & dMData$year == 2005] <- NA
dMData$length[dMData$tagNumberCH=='257C67CA48' ] <- NA
dMData$length[dMData$tagNumberCH=='1BF20EB7A4' & dMData$season == 4 & dMData$year == 2008] <- NA
dMData$length[dMData$tagNumberCH=='00088D215D' & dMData$season == 4 & dMData$year == 2010] <- NA

**Comment by evanchildress** [comment]
Most of these were dealt with, those that have not been dealt with are flagged during the existing checks, so they should be dealt with along with other issues that have been identified.
