### ISSUE TITLE
sample 92 in west brook doesn't have any fish

### ISSUE THREAD

**Issue by evanchildress** [Conte-Ecology/westBrookData#32]
tribs have fish but main stem does not for sample_name=='92' or sample_number==81 from createCoreData. Do these fish not exist in the database or are the somehow lost?

**Comment by evanchildress** [comment]
There aren't any in the raw_tags_trout_wb table, so they must not be in the raw data as it was imported. Grab those again and see if it resolves.

**Comment by bletcher** [comment]
was that a winter sample?

On Mon, Jan 25, 2016 at 5:15 PM, evanchildress notifications@github.com
wrote:

> There aren't any in the raw_tags_trout_wb table, so they must not be in
> the raw data as it was imported. Grab those again and see if it resolves.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Conte-Ecology/westBrookData/issues/32#issuecomment-174692887
> .

## 

 Silvio O. Conte Anadromous Fish Research Center, U.S. Geological Survey
 P.O. Box 796 -- One Migratory Way
 Turners Falls, MA 01376
 (413) 863-3803
 Cell: (413) 522-9417
 FAX (413) 863-9810

ben_letcher@usgs.gov
bletcher@eco.umass.edu
http://www.lsc.usgs.gov/?q=cafb-research

**Comment by evanchildress** [comment]
west brook was not sampled then
