### ISSUE TITLE
above below sections

### ISSUE THREAD

**Issue by evanchildress** [Conte-Ecology/westBrookData#33]

**Comment by evanchildress** [comment]
fixed the naming inconsistency, but need to decide how to deal with these in createCmrData(). Should they be excluded?

**Comment by bletcher** [comment]
they have been in analyses to date. but someone may want to do an analysis
that includes them - known alive, but off study site. Can we make it an
option to include with the default of not include?

On Thu, Jan 28, 2016 at 4:56 PM, evanchildress notifications@github.com
wrote:

> fixed the naming consistency, but need to decide how to deal with these in
> createCmrData(). Should they be excluded?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Conte-Ecology/westBrookData/issues/33#issuecomment-176439463
> .

## 

 Silvio O. Conte Anadromous Fish Research Center, U.S. Geological Survey
 P.O. Box 796 -- One Migratory Way
 Turners Falls, MA 01376
 (413) 863-3803
 Cell: (413) 522-9417
 FAX (413) 863-9810

ben_letcher@usgs.gov
bletcher@eco.umass.edu
http://www.lsc.usgs.gov/?q=cafb-research

**Comment by evanchildress** [comment]
yup, done. We'd need to revisit the known alive but off site thing in addKnownZ() to make the scenario you described possible.
