### ISSUE TITLE
fillSizeLocation() needs to be by species

### ISSUE THREAD

**Issue by evanchildress** [Conte-Ecology/westBrookData#37]

**Comment by evanchildress** [comment]
done

**Comment by bletcher** [comment]
sweet

On Thu, Feb 11, 2016 at 4:57 PM, evanchildress notifications@github.com
wrote:

> done
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Conte-Ecology/westBrookData/issues/37#issuecomment-183076002
> .

## 

 Silvio O. Conte Anadromous Fish Research Center, U.S. Geological Survey
 P.O. Box 796 -- One Migratory Way
 Turners Falls, MA 01376
 (413) 863-3803
 Cell: (413) 522-9417
 FAX (413) 863-9810

ben_letcher@usgs.gov
bletcher@eco.umass.edu
http://www.lsc.usgs.gov/?q=cafb-research
