### ISSUE TITLE
4.	wb jimmy section 2 has a file that has a start date of 8/1/2012 and an end date of 2/17/2012; can you track down the real end date (or start date) for that?  

### ISSUE THREAD

**Issue by tdube2014** [Conte-Ecology/westBrookData#46]
wb_jimmySection2_5049_08012012-02172012 same as wb_jimmySection2_5049_08012012-10292012 delete the above data file (wb_jimmySection2_5049_08012012-02172012) redundant.

**Comment by evanchildress** [comment]
done
