### ISSUE TITLE
get_tag_data

### ISSUE THREAD

**Issue by matthewodonnell** [Conte-Ecology/westBrookData#51]
need to add stanley seawater antenna data (which is the set of antennas located in section 1) to the get_tag_data table so that fish that are last detected on the seawater antennas get coded as emmigrants

**Comment by evanchildress** [comment]
are all antenna detections in Stanley at study area boundaries? It looks like there are just two locations with replicates for directionality. Is the upper location (river meter 430) at the top of the study site?

**Comment by matthewodonnell** [comment]
no, just the antennas in section 1 (river meter values less than 40).  antennas at river meter 430 are only a quarter of the way into the study site

**Comment by evanchildress** [comment]
done
