### ISSUE TITLE
cohort assignment is wrong for fish 257c689ade in Stanley

### ISSUE THREAD

**Issue by evanchildress** [Conte-Ecology/westBrookData#53]

**Comment by matthewodonnell** [comment]
Per the size bins, the assignment is correct for sample 6.  What is incorrect, is the length and weight for this tag number in sample 14; looks like the wrong data was entered for that tag number in the Tags - Stanley table

**Comment by evanchildress** [comment]
added this to 'declare_data_errors' so that the length and weight are turned to NA in the database.
