### ISSUE TITLE
need to be sure signal, rms, and ph are the right format (numeric?)

### ISSUE THREAD

**Issue by evanchildress** [Conte-Ecology/westBrookData#58]
In form_data_antenna_log.R I didn't know what format to make these because they are all NA for the 2009 data.

**ALSO!** Be sure that the treatment of current is correct. Currently it takes a single number as the current measurement for arrival and departure, and interprets two numbers separated by "/" as arrival/departure

**Comment by matthewodonnell** [comment]
Can you give me access to 'data_antenna_log'

**Comment by evanchildress** [comment]
Done, but it probably isn't useful yet. We are in the testing phase for this. The data are not all in there. This issue is really just a reminder for me to talk with Todd about these.

**Comment by evanchildress** [comment]
done
