### ISSUE TITLE
dates for jimmy antennas at 5020 and 5024.1 are backwards somewhere

### ISSUE THREAD

**Issue by evanchildress** [Conte-Ecology/westBrookData#59]
detection data says 5020 was deployed in 2009-2010, but deployment data say 2003-2005. Vice versa for 5024.1

Todd, can you figure out which one is right and either fix the deployment or tell me that it is the detection data?

**Comment by tdube2014** [comment]
**detection data says 5020 was deployed in 2009-2010, but deployment data say 2003-2005. The detection data is labeled wrong**.

 It should be 5024.1.  I have 5020 and 5024.1 reversed when I labeled them earlier. Deployment table is correct.

**Comment by evanchildress** [comment]
I switched them as part of the import process for the detection data (processedData/antenna_locations.csv)
