### ISSUE TITLE
antenna at 4830 deployment data seems wrong

### ISSUE THREAD

**Issue by evanchildress** [Conte-Ecology/westBrookData#63]
There are log entries back to 6/6/2012, but there are no detections until 2/13/2013. Need to sort out when it was in and working.

**Comment by tdube2014** [comment]
There are two files, wb_mitchellAbove_4809_06062012_07042012.A and wb_mitchellAbove_4809_08122012-02072013 that are labeled wrong. replace 4809 in both files with 4830 that will fix the deployment  issue. The deployment date of 6/6/2012 is correct, double checked data and log files. This fixes both the 4808 and 4830 antenna figures. Both file that need to be corrected are in the Mitchell above 2012 folder.

**Comment by evanchildress** [comment]
fixed as described above
