### ISSUE TITLE
5020 has missing data 7/05 through 10/05

### ISSUE THREAD

**Issue by evanchildress** [Conte-Ecology/westBrookData#64]

**Comment by evanchildress** [comment]
I'm not seeing anything suspicious here.

**Comment by tdube2014** [comment]
Buffer count is filled in for these days in log sheet. Should have data somewhere.

**Comment by tdube2014** [comment]
Filled from The end of July to beginning of September. Found files that had been set aside and not input.
There were also files for, 5524 Above and  Mitchell 4808 and 4797.  Evan is going to add this data. There are still two Jimmy files that have been set aside. Not sure of the location. Definitely Jimmy but unsure of the antenna. Set aside until more gaps are filled.

**Comment by tdube2014** [comment]
did not want to close still open

**Comment by evanchildress** [comment]
data added
