### ISSUE TITLE
missing data for antenna 5049.3 10/2011 to 3/2012

### ISSUE THREAD

**Issue by evanchildress** [Conte-Ecology/westBrookData#66]

**Comment by evanchildress** [comment]
There is also extra data in 5096.3 during this period for much of it, which could be the missing data.

**Comment by tdube2014** [comment]
5096 should not be deployed until 4/9/14

**Comment by tdube2014** [comment]
Compared extra 5096 data with 5049 data. March 2012 5049 data is dominated by fish E277. That same tag is on the earlier 5096 file in late Feb 2012. Unlikely fish is moving from another antenna at this time. Also 5096 is not deployed, Change extra 5096 data to 5049. This will fill some of the gap.

**Comment by evanchildress** [comment]
There was one mislabeled file, changed from 5096 to wb_jimmySection2_5049_11012011-02232012_.TXT which should fill this gap.
