### ISSUE TITLE
antenna 5116.8 has data after it was pulled on 3/28/2011

### ISSUE THREAD

**Issue by evanchildress** [Conte-Ecology/westBrookData#68]

**Comment by tdube2014** [comment]
Only one tag. determined to be a test tag (3/28/2011) Actual removal date will be 6/15/2011. looked thru PDA files no tags after Nov 2010. Note, fairly sure there was a fall 2011 deployment (post theft) that netted no tags. I can find no data or log sheets for this time. I will look on my backup hard drive to look for data. I will close this out once I have checked hard drive.

**Comment by evanchildress** [comment]
Changed deplyment to end at theft. No data from after theft although there were files.
