### ISSUE TITLE
Change 5116 removal date to 6/15/2011

### ISSUE THREAD

**Issue by tdube2014** [Conte-Ecology/westBrookData#70]
There was a Pre theft removal date  of 6/15/2011
Post Theft was incorrect I had 10/10/2011 - 3/28/2011 definitely not right. I am currently double checking for data in the Fall of 2011. no data sheets or data available at this time.

**Comment by evanchildress** [comment]
need end deployment at theft because it did not appear to be deployed later

**Comment by evanchildress** [comment]
duplicate of 68
